src/domain/Cart.java
package domain;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;


public class Cart {
    private Map<String ,CartItem> itemMap=new HashMap<String,CartItem>();
    private Double total=0.0;

    /**
     * 获取所有购物项
     * @return
     */
    public Collection<CartItem> getCartItems(){
        return itemMap.values();
    }

    public Map<String, CartItem> getItemMap() {
        return itemMap;
    }

    public void setItemMap(Map<String, CartItem> itemMap) {
        this.itemMap = itemMap;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * 加入购物车
     * @param item
     */
    public void add2Cart(CartItem item){
        String pid=item.getProduct().getPid();

        if(itemMap.containsKey((pid))){
            CartItem oItem =itemMap.get(pid);
            oItem.setCount(oItem.getCount()+item.getCount());
        }else {
            itemMap.put(pid,item);
        }

        total+=item.getSubtotal();
    }
    /**
     * 移除购物车
     * @param pid
     */
    public void removeFromCart(String pid){
        //map中移除购物项
        CartItem item = itemMap.remove(pid);

        total-=item.getSubtotal();
    }
    /**
     * 清空购物车
     */
    public void cleanCart(){
        itemMap.clear();
        total=0.0;
    }
}

src/domain/Order.java
package domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Order {
    //订单编号
    private String oid;
    //下单时间
    private Date ordertime;
    //总额
    private double total;
    //订单装状态 0未付款 1已付款 2已发货 3已签收完成
    private Integer state;
    //收货地址
    private String address;
    //收件人
    private String name;
    //联系方式
    private String telephone;
    //订单归属
    private User user;
    //当前订单包含的订单项
    private List<OrderItem> items=new ArrayList<>();

    public String getOid() {
        return oid;
    }

    public void setOid(String oid) {
        this.oid = oid;
    }

    public Date getOrdertime() {
        return ordertime;
    }

    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    public double getTotal() {
        return total;
    }

    public void setTotal(double total) {
        this.total = total;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
    }

    private List<OrderItem> orderItemList;

    public List<OrderItem> getOrderItemList() {
        return orderItemList;
    }
    public void setOrderItemList(List<OrderItem> orderItemList) {
        this.orderItemList = orderItemList;
    }
}

src/web/cartServlet/CartServlet.java
package web.cartServlet;

import domain.Cart;
import domain.CartItem;
import domain.Product;
import service.ProductService;
import service.impl.ProductServiceImpl;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * 购物车模块
 * @author PPL
 *
 */
@WebServlet("/cartServlet")
public class CartServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        /*//获取pid count
        String pid=request.getParameter("pid");
        int count=Integer.parseInt(request.getParameter("count"));
        //封装cartitem
        //调用service获取product
        ProductService ps=new ProductServiceImpl();
        Product product=ps.getById(pid);
        //创建cartitem
        CartItem cartItem=new CartItem(product,count);
        //获取购物车
        Cart cart=getCart(request);
        cart.add2Cart(cartItem);
        //重定向
        response.sendRedirect(request.getContextPath()+"/index.jsp");
        //request.getRequestDispatcher("/cart.jsp").forward(request,response);*/
    }

    /**
     * 获取购物车
     * @param request
     * @return
     */
    private Cart getCart(HttpServletRequest request) {
        Cart cart=(Cart)request.getSession().getAttribute("cart");
        if(cart==null){
            cart=new Cart();
            request.getSession().setAttribute("cart",cart);
        }
        return cart;

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        this.doPost(request, response);
    }
}

src/web/cartServlet/OrderServlet.java
package web.cartServlet;

import constant.Constant;
import domain.*;
import service.OrderService;
import service.impl.OrderServiceImpl;
import util.UuidUtil;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.UUID;

@WebServlet("/orderServlet")
public class OrderServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        //检测登录状态
        User user =(User) request.getSession().getAttribute("user");
        if(user==null){
            request.setAttribute("wdl","请先登录");
            request.getRequestDispatcher("/login.jsp").forward(request,response);
        }
        //获取购物车
        Cart cart=(Cart)request.getSession().getAttribute("cart");

        //封装对象





        //创建对象
        Order order=new Order();
        //设置oid
        order.setOid(UuidUtil.getUuid());
        //设置Ordertime
        order.setOrdertime(new Date());
        //设置购物车total
        order.setTotal(cart.getTotal());
        //设置state
        order.setState(Constant.order_weifukuan);
        //设置user
        order.setUser(user);
        //设置订单项表 items 并遍历购物项列表
        for(CartItem ci:cart.getCartItems()){
            //封装形成orderItem
            //创建orderitem
            OrderItem oi=new OrderItem();
            //设置itemid
            oi.setItemid(UuidUtil.getUuid());
            //从ci中获取count
            oi.setCount(ci.getCount());
            //设置subtotal
            oi.setSubtotal(ci.getSubtotal());
            //设置protect
            oi.setProduct(ci.getProduct());
            //设置order
            oi.setOrder(order);
            //将orderitem加入order的items
            order.getItems().add(oi);
        }

        //调用orderService保存
        OrderService os=new OrderServiceImpl();
        try {
            os.save(order);
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        cart.cleanCart();
        //转发

//        request.setAttribute("bean",order);
//        response.sendRedirect(request.getContextPath()+"/fahuo.jsp");

        HttpSession session = request.getSession();
        session.setAttribute("bean",order);
        response.sendRedirect(request.getContextPath()+"/order.jsp");
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        this.doPost(request, response);
    }
}

src/web/servlet/LoginServlet.java
package web.servlet;

import domain.User;
import org.apache.commons.beanutils.BeanUtils;
import service.UserService;
import service.impl.UserServiceImpl;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.Map;
/**
 * 用户登录
 * @author PPL
 *
 */
@WebServlet("/loginServlet")
public class LoginServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        //设置编码
        request.setCharacterEncoding("utf-8");
        Integer count=0;//总在线人数
        //2.获取数据
        //获取验证码
        String verifycode=request.getParameter("verifycode");
        //3.校验验证码
        HttpSession session=request.getSession();
        String checkcode_server=(String)session.getAttribute("CHECKCODE_SERVER");
        //一次性
        session.removeAttribute("CHECKCODE_SERVER");
        session.removeAttribute("login_msg");
        if(checkcode_server==null||!checkcode_server.equalsIgnoreCase(verifycode)){
            //验证码不正确，返回首页
            //提示信息
            request.setAttribute("login_msg","验证码错误");
            //跳转登录页面
            request.getRequestDispatcher("/login.jsp").forward(request,response);
            return;
        }

        Map<String,String[]> map=request.getParameterMap();
        //4.封装User对象
        User user=new User();
        try {
            BeanUtils.populate(user,map);
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }

        //调用service查询
        UserService service=new UserServiceImpl();
        User loginUser=service.login(user);
        //判断是否登录成功
        if(loginUser!=null){

            //登陆成功，将用户存入session
            session.setAttribute("user",loginUser);
            //跳转页面
            response.sendRedirect(request.getContextPath()+"/index.jsp");

            ServletContext servletContext = request.getServletContext();
            servletContext.setAttribute("count",++count);
        }else{
            //登录失败
            request.setAttribute("login_msg","用户名或密码错误");
            //跳转登录
            request.getRequestDispatcher("/login.jsp").forward(request,response);

        }

    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        this.doPost(request, response);
    }
}

web/bottom.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="js/bootstrap.min.js"></script>
    <!--引入图标-->
    <link rel="shortcut icon" href="favicon.ico"/>
    <!--引入初始化样式文件-->
    <link rel="stylesheet" href="css/pdd_init.css">
    <!--引入公共的样式文件-->
    <link rel="stylesheet" href="css/commons.css">
</head>
<body>
<footer class="footer" >
    <div class="w" >
        <div class="mod_service">
            <ul>
                <li>
                    <h5 id="code1"></h5>
                    <div class="service_txt">
                        <h4>正品保证</h4>
                        <p>诚信优购，假一赔十</p>
                    </div>
                </li>
                <li>
                    <h5 id="code2"></h5>
                    <div class="service_txt">
                        <h4>极速物流</h4>
                        <p>物流提速，72时必达</p>
                    </div>
                </li>
                <li>
                    <h5 id="code3"></h5>
                    <div class="service_txt">
                        <h4>无忧售后</h4>
                        <p>7天无理由退换货</p>
                    </div>
                </li>
                <li>
                    <h5 id="code4"></h5>
                    <div class="service_txt">
                        <h4>特色服务</h4>
                        <p>专属客服，24小时在线</p>
                    </div>
                </li>
            </ul>
        </div>
        <div class="mod_help">
            <dl>
                <dt>服务指南</dt>
                <dd><a href="#">购物流程</a></dd>
                <dd><a href="#">会员介绍</a></dd>
                <dd><a href="#">生活旅行</a></dd>
                <dd><a href="#">常见问题</a></dd>
                <dd><a href="#">大型家电</a></dd>
                <dd><a href="#">联系客服</a></dd>
            </dl>
            <dl>
                <dt>优购保障</dt>
                <dd><a href="#">发票保障</a></dd>
                <dd><a href="#">会员介绍</a></dd>
                <dd><a href="#">缺货赔付</a></dd>
            </dl>
            <dl>
                <dt>支付方式</dt>
                <dd><a href="#">快捷支付</a></dd>
                <dd><a href="#">信用卡</a></dd>
                <dd><a href="#">优购宝</a></dd>
                <dd><a href="#">大象草呗</a></dd>
                <dd><a href="#">货到付款</a></dd>
            </dl>
            <dl>
                <dt>商家服务</dt>
                <dd><a href="#">优购规则</a></dd>
                <dd><a href="#">商家入驻</a></dd>
                <dd><a href="#">商家中心</a></dd>
                <dd><a href="#">常见问题</a></dd>
                <dd><a href="#">优购智库</a></dd>
                <dd><a href="#">物流服务</a></dd>
            </dl>
            <dl>
                <dt>服务指南</dt>
                <dd><a href="#">购物流程</a></dd>
                <dd><a href="#">会员介绍</a></dd>
                <dd><a href="#">生活旅行</a></dd>
                <dd><a href="#">常见问题</a></dd>
                <dd><a href="#">大型家电</a></dd>
                <dd><a href="#">联系客服</a></dd>
            </dl>
            <dl>
                <dt>帮助中心</dt>
                <dd>
                    <img src="img/qrcode.png" style="width: 90px;height: 90px" alt="">
                    拼优购客户端
                </dd>
            </dl>
        </div>
        <div class="mod_copyright">
            <div class="links">
                <a href="#">入驻优购国际</a>|
                <a href="#">校园招聘</a>|
                <a href="#">关于我们</a>|


                <a href="#">帮助中心</a>|
                <a href="#">下载App</a>|
                <a href="#">消费者保障</a>|
                <a href="#">维权投诉指引</a>|
                <a href="#">廉正举报</a>|
                <a href="#">服务协议</a>|
                <a href="#">隐私政策</a>|
                <a href="#">征求意见</a>|
                <a href="#">Investor Relations</a>|

            </div>
            <div class="copyright">
                拼优购电子商务平台

            </div>
        </div>
    </div>
</footer>
</body>
</html>

web/cart.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>购物车</title>

    <!--引入图标-->
    <link rel="shortcut icon" href="favicon.ico"/>
    <!--引入初始化样式文件-->
    <link rel="stylesheet" href="css/pdd_init.css">
    <!--引入页面css-->
    <link rel="stylesheet" href="css/login.css">
    <link rel="stylesheet" type="text/css" href="css/shopping-cars.css"/>
    <link rel="stylesheet" type="text/css" href="css/reset.css"/>
    <!--引入公共的样式文件-->
    <link rel="stylesheet" href="css/commons.css">
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/top.js"></script>
    <script src="js/foot.js"></script>
    <script src="js/myCar.js" type="text/javascript"></script>
    <!-- 引入自定义css文件 style.css -->

    <style>


        .carousel-inner .item img {
            width: 100%;
            height: 300px;
        }

        .container .row div {
            /* position:relative;
 float:left; */
        }

        font {
            color: #3164af;
            font-size: 18px;
            font-weight: normal;
            padding: 0 10px;
        }

    </style>
    <script type="text/javascript">

        /*单个删除*/
        function removeFromCart(ccid) {
            if (confirm("您忍心抛弃我吗?")) {
                location.href = "${pageContext.request.contextPath}/CartItemServlet?method=batchDelete&cartItemIds=" + ccid;
            }
        }
        function batchDelete() {
            // 1. 获取所有被选中条目的复选框
            // 2. 创建一数组，把所有被选中的复选框的值添加到数组中
            // 3. 指定location为CartItemServlet，参数method=batchDelete，参数cartItemIds=数组的toString()
            var cartItemIdArray = new Array();
            $(":checkbox[name=checkboxBtn]").each(function() {
                if(this.checked){
                    cartItemIdArray.push($(this).val());//把复选框的值添加到数组中
                }

            });
            //alert(cartItemIdArray);
            if (confirm("您忍心抛弃我们吗?")) {
                location.href = "${pageContext.request.contextPath}/CartItemServlet?method=batchDelete&cartItemIds=" + cartItemIdArray;
            }

        }

    </script>
</head>

<body>


<%@include file="top.jsp" %>
<hr style="border-bottom: 2px solid #b1191a;">
<div class="container">
    <div class="row">
        <c:if test="${empty cartItemList }">
            <h3>芜湖！购物车的肚子空空如也，赶紧来填饱我吧@_@</h3>

        </c:if>
        <c:if test="${not empty cartItemList}">
            <%--<div style="margin:0 auto; margin-top:10px;width:950px;">
                <strong style="font-size:16px;margin:5px 0;">购物车详情</strong>
                <table class="table table-bordered">
                    <tbody>
                    <tr class="warning">
                        <th>图片</th>
                        <th>商品</th>
                        <th>价格</th>
                        <th>数量</th>
                        <th>小计</th>
                        <th>操作</th>
                    </tr>
                    <c:forEach items="${cart.cartItems }" var="ci">
                        <tr class="active">
                            <td width="60" width="40%">
                                <input type="hidden" name="id" value="22">
                                <img src="goods/${ci.product.pimages}" width="70" height="60">
                            </td>
                            <td width="30%">
                                <a target="_blank">${ci.product.pname}</a>
                            </td>
                            <td width="20%">
                                ￥${ci.product.good_price}
                            </td>
                            <td width="10%">
                                <input type="text" readonly="readonly" name="quantity" value="${ci.count }"
                                       maxlength="4" size="10">
                            </td>
                            <td width="15%">
                                <span class="subtotal">￥${ci.subtotal }</span>
                            </td>
                            <td>
                                <a href="javascript:void(0);" onclick="removeFromCart('${ci.product.pid}')"
                                   class="delete">删除</a>
                            </td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </div>

            <div style="margin-right:130px;">
                <div style="text-align:right;">
                    商品金额: <strong style="color:#ff6600;">￥${cart.total }元</strong>
                </div>
                <div style="text-align:right;margin-top:10px;margin-bottom:10px;">
                    <a href="${pageContext.request.contextPath }/cartDelAllServlet?method=doPost" id="clear"
                       class="clear">清空购物车</a>
                    <a href="${pageContext.request.contextPath }/orderServlet">
                        <input type="button" width="100" value="提交订单" name="submit" border="0" style="background: url('images/register.gif') no-repeat scroll 0 0 rgba(0, 0, 0, 0);
                        height:35px;width:100px;color:white;">
                    </a>
                </div>
            </div>--%>
            <div class="list">
                <div class="information">
                    <div class="Commodity-information">
                        <div class="w-w1 fl">
                            <input type="checkbox" class="checkbox fl" id="selectAll" name="selectAll" checked="checked"/>
                            <span class="all fl" for="selectAll">全选</span>
                            <div class="clear"></div>
                        </div>
                        <div class="w-w2 fl">
                            <span class="all fl">商品信息</span>
                            <div class="clear"></div>
                        </div>
                        <div class="w-w3 fl">
                            <span class="all">单价</span>
                        </div>
                        <div class="w-w4 fl">
                            <span class="all">数量</span>
                        </div>
                        <div class="w-w5 fl">
                            <span class="all fl">小计</span>
                            <div class="clear"></div>
                        </div>
                        <div class="w-w6 fr">
                            <span class="all fl">操作</span>
                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>
                    </div>
                </div>
                <ul class="cart-grouplist">

                    <c:forEach items="${cartItemList}" var="cartItem">
                    <li>
                        <div class="list-list">
                            <div class="buttona fl">
                                <input type="checkbox" class="checkbox" name="checkboxBtn" checked="checked" value="${cartItem.cartItemId}"/>
                            </div>
                            <div class="photo fl">
                                <img src="goods/${cartItem.product.pimages}"/>
                            </div>
                            <div class="nameCon fl">
                                <a class="sleep-yi" href="#">${cartItem.product.pname}</a>
                                <div class="color">
                                    <a href="#">${cartItem.product.pdesc}</a>
                                </div>
                            </div>
                            <span class="pricea fl">￥</span>
                            <span class="priceb fl">${cartItem.product.good_price}</span>
                            <div class="u-selnum fl">

                                <a class="reduction fl" id="${cartItem.cartItemId}Jian">-</a>
                                <input class="j-input fl" type="text" readonly="readonly" value="${cartItem.count}" id="${cartItem.cartItemId}Count"/>
                                <a class="sign fl" id="${cartItem.cartItemId}Jia">+</a>
                                <div class="clear"></div>

                            </div>
                            <span class="price11 fl">￥</span>
                            <span class="price1 fl" id="${cartItem.cartItemId}Subtotal">${cartItem.subtotal }</span>
                            <div class="move-del fl">
                                <a class="delect" href="javascript:void(0);" onclick="removeFromCart('${cartItem.cartItemId}')">
                                    删除商品
                                </a>
                                <div class="clear"></div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </li>
                    </c:forEach>

                </ul>

                <div class="combined">
                    <div class="combined-del">
                        <%--<input type="checkbox" class="checkbox"/>--%>

                        <p class="batch-del" href="javascript:void(0);" onclick="batchDelete()">删除选中</p>

                    </div>
                    <div class="combined-button fr" >
                        <%--<a href="${pageContext.request.contextPath }/orderServlet">
                            <button id="btn">下&nbsp;&nbsp;单</button>
                        </a>--%>
                            <a href="javascript:order()">
                                <button id="btn">结&nbsp;&nbsp;算</button>
                            </a>
                    </div>
                    <form id="orderForm" action="<c:url value='/CartItemServlet'/>" method="post">
                        <input type="hidden" name="cartItemIds" id="cartItemIds"/>
                        <input type="hidden" name="total" id="hiddenTotal"/>
                        <input type="hidden" name="method" value="loadCartItems"/>
                    </form>
                    <div class="cost fr">
                        <div class="shang">
                            <span class="cost-cost">应付总额：</span>
                            <span class="cost-price1">￥</span>
                            <span type="text" class="cost-price" id="total"></span>
                        </div>
                        <div class="line-line fr">
                            <a href="goods-details.html">
                                <span>再购</span>
                                <span>0.00</span>
                                <span>免邮，去凑单></span>
                            </a>
                        </div>
                    </div>
                    <div class="activity fr">
                        <div class="activity-line">

                        </div>
                        <div class="activitylist-line">

                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </c:if>
    </div>
</div>

<div id="shopping_foot"></div>
</body>
</html>

web/fahuo.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>订单</title>

    <!--引入图标-->
    <link rel="shortcut icon" href="favicon.ico"/>
    <!--引入初始化样式文件-->
    <link rel="stylesheet" href="css/pdd_init.css">
    <!--引入注册页面css-->
    <link rel="stylesheet" href="css/login.css">
    <!--引入公共的样式文件-->
    <link rel="stylesheet" href="css/commons.css">
    <style>
        body {
            margin-top: 20px;
            margin: 0 auto;
        }

        .carousel-inner .item img {
            width: 100%;
            height: 300px;
        }
    </style>
</head>
<body>
<%@include file="top.jsp" %>
<div class="container">
    <div class="row">

        <div style="margin:0 auto;margin-top:10px;width:950px;">
            <strong>订单详情</strong>
            <table class="table table-bordered">
                <tbody>
                <tr class="warning">
                    <th colspan="2">订单编号:${bean.oid } </th>
                    <th colspan="1">
                        <c:if test="${bean.state == 0 }">去付款</c:if>
                        <c:if test="${bean.state == 1 }">已付款</c:if>
                        <c:if test="${bean.state == 2 }">确认收货</c:if>
                        <c:if test="${bean.state == 3 }">已完成</c:if>
                    </th>
                    <th colspan="2">时间:<fmt:formatDate value="${bean.ordertime }" pattern="yyyy-MM-dd HH:mm:ss"/>
                    </th>
                </tr>
                <tr class="warning">
                    <th>图片</th>
                    <th>商品</th>
                    <th>价格</th>
                    <th>数量</th>
                    <th>小计</th>
                </tr>
                <c:forEach items="${bean.items }" var="oi">
                    <tr class="active">
                        <td width="60" width="40%">
                            <input type="hidden" name="id" value="22">
                            <img src="goods/${oi.product.pimages}" width="70" height="60">
                        </td>
                        <td width="30%">
                            <a target="_blank">${oi.product.pname}</a>
                        </td>
                        <td width="20%">
                            ￥${oi.product.good_price}
                        </td>
                        <td width="10%">
                                ${oi.count}
                        </td>
                        <td width="15%">
                            <span class="subtotal">￥${oi.subtotal}</span>
                        </td>
                    </tr>
                </c:forEach>
                </tbody>
            </table>
        </div>

        <div style="text-align:right;margin-right:120px;">
            商品金额: <strong style="color:#ff6600;">￥${bean.total }元</strong>
        </div>

    </div>

    <div style="padding-left: 830px ; padding-top: 20px">
            <a href="${pageContext.request.contextPath}/deliverServlet?oid=${bean.oid}" class="btn btn-primary btn-lg active" role="button">自己发货</a>
            <p href="#" class="btn btn-default btn-lg active" role="button">等待发货</p>

    </div>

</div>

<iframe src="bottom.jsp" width="100%" height="400" scrolling="no" frameborder="0"></iframe>
</body>
</html>

web/head.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<script src="js/jquery-3.2.1.min.js"></script>
<div class="the_navitems">
    <ul id="head">
        <%--<li><a href="#">服装城</a></li>
        <li><a href="#">电器城</a></li>
        <li><a href="#">生鲜超市</a></li>
        <li><a href="#">医药馆</a></li>
        <li><a href="#">营业厅</a></li>
        <li><a href="#">魅力惠</a></li>
        <li><a href="#">飞猪旅行</a></li>
        <li><a href="#">苏宁易购</a></li>--%>
    </ul>
</div>
<script type="text/javascript">
    $(function () {
        //发送ajax查询所有分类
        $.post("${pageContext.request.contextPath}/categoryServlet",{"method":"doPost"},function(obj) {
            // alert(obj);
            $(obj).each(function () {
                //alert(this.cname);
                $("#head").append("<li><a href='${pageContext.request.contextPath}/categoryPageServlet?method=doPost&cid="+this.cid+"'>"+this.cname+ "</a></li>");
            })
        },"json");
    })
</script>

web/welcome.jsp
d<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>首页</title>

    <!-- 1. 导入CSS的全局样式 -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- 2. jQuery导入，建议使用1.9以上的版本 -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <!-- 3. 导入bootstrap的js文件 -->
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript">
    </script>
</head>
<body>
<div>
    ${user.name},欢迎您！
</div>
<div align="center">
    <a
            href="${pageContext.request.contextPath}/findUserByPageServlet" style="text-decoration:none;font-size:33px">查询所有用户信息
    </a>
</div>
</body>
</html>